### PR TITLE
chore: Test 3.3.4-RC

### PR DESCRIPTION
**Pull request by He-Pin**
Test 3.3.4-RC1

### CODE REVIEW

**Comment by He-Pin** [comment]
@WojciechMazur

It now cause mima issue. https://github.com/apache/pekko-connectors/actions/runs/10018168453/job/27693229254?pr=749#step:5:4779

**Comment by pjfanning** [comment]
```
[error] pekko-connectors-ironmq: Failed binary compatibility check against org.apache.pekko:pekko-connectors-ironmq_3:1.0.2! Found 13 potential problems
[error]  * static method apply(scala.collection.immutable.List)org.apache.pekko.stream.connectors.ironmq.Message#Ids in class org.apache.pekko.stream.connectors.ironmq.Message#Ids has a different generic signature in current version, where it is (Lscala/collection/immutable/List<Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;>;)Lorg/apache/pekko/stream/connectors/ironmq/Message$Ids; rather than (Lscala/collection/immutable/List<Ljava/lang/String;>;)Lorg/apache/pekko/stream/connectors/ironmq/Message$Ids;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.Message#Ids.apply")
[error]  * method this(scala.collection.immutable.List)Unit in class org.apache.pekko.stream.connectors.ironmq.Message#Ids has a different generic signature in current version, where it is (Lscala/collection/immutable/List<Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;>;)V rather than (Lscala/collection/immutable/List<Ljava/lang/String;>;)V. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.Message#Ids.this")
[error]  * method ids()scala.collection.immutable.List in class org.apache.pekko.stream.connectors.ironmq.Message#Ids has a different generic signature in current version, where it is ()Lscala/collection/immutable/List<Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;>; rather than ()Lscala/collection/immutable/List<Ljava/lang/String;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.Message#Ids.ids")
[error]  * method copy(scala.collection.immutable.List)org.apache.pekko.stream.connectors.ironmq.Message#Ids in class org.apache.pekko.stream.connectors.ironmq.Message#Ids has a different generic signature in current version, where it is (Lscala/collection/immutable/List<Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;>;)Lorg/apache/pekko/stream/connectors/ironmq/Message$Ids; rather than (Lscala/collection/immutable/List<Ljava/lang/String;>;)Lorg/apache/pekko/stream/connectors/ironmq/Message$Ids;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.Message#Ids.copy")
[error]  * synthetic method copy$default$1()scala.collection.immutable.List in class org.apache.pekko.stream.connectors.ironmq.Message#Ids has a different generic signature in current version, where it is ()Lscala/collection/immutable/List<Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;>; rather than ()Lscala/collection/immutable/List<Ljava/lang/String;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.Message#Ids.copy$default$1")
[error]  * method _1()scala.collection.immutable.List in class org.apache.pekko.stream.connectors.ironmq.Message#Ids has a different generic signature in current version, where it is ()Lscala/collection/immutable/List<Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;>; rather than ()Lscala/collection/immutable/List<Ljava/lang/String;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.Message#Ids._1")
[error]  * method apply(scala.collection.immutable.List)org.apache.pekko.stream.connectors.ironmq.Message#Ids in object org.apache.pekko.stream.connectors.ironmq.Message#Ids has a different generic signature in current version, where it is (Lscala/collection/immutable/List<Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;>;)Lorg/apache/pekko/stream/connectors/ironmq/Message$Ids; rather than (Lscala/collection/immutable/List<Ljava/lang/String;>;)Lorg/apache/pekko/stream/connectors/ironmq/Message$Ids;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.Message#Ids.apply")
[error]  * static method atLeastOnceFlow(java.lang.String,org.apache.pekko.stream.connectors.ironmq.IronMqSettings)org.apache.pekko.stream.scaladsl.Flow in class org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer has a different generic signature in current version, where it is (Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;)Lorg/apache/pekko/stream/scaladsl/Flow<Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;Lorg/apache/pekko/stream/connectors/ironmq/scaladsl/Committable;>;Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;Lorg/apache/pekko/NotUsed;>; rather than (Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;)Lorg/apache/pekko/stream/scaladsl/Flow<Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;Lorg/apache/pekko/stream/connectors/ironmq/scaladsl/Committable;>;Ljava/lang/String;Lorg/apache/pekko/NotUsed;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer.atLeastOnceFlow")
[error]  * static method atLeastOnceFlow(java.lang.String,org.apache.pekko.stream.connectors.ironmq.IronMqSettings,org.apache.pekko.stream.scaladsl.Flow)org.apache.pekko.stream.scaladsl.Flow in class org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer has a different generic signature in current version, where it is <ToCommit:Ljava/lang/Object;CommitResult:Ljava/lang/Object;CommitMat:Ljava/lang/Object;>(Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;Lorg/apache/pekko/stream/scaladsl/Flow<TToCommit;TCommitResult;TCommitMat;>;)Lorg/apache/pekko/stream/scaladsl/Flow<Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;TToCommit;>;Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;TCommitResult;>;TCommitMat;>; rather than <ToCommit:Ljava/lang/Object;CommitResult:Ljava/lang/Object;CommitMat:Ljava/lang/Object;>(Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;Lorg/apache/pekko/stream/scaladsl/Flow<TToCommit;TCommitResult;TCommitMat;>;)Lorg/apache/pekko/stream/scaladsl/Flow<Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;TToCommit;>;Lscala/Tuple2<Ljava/lang/String;TCommitResult;>;TCommitMat;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer.atLeastOnceFlow")
[error]  * static method flow(java.lang.String,org.apache.pekko.stream.connectors.ironmq.IronMqSettings)org.apache.pekko.stream.scaladsl.Flow in class org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer has a different generic signature in current version, where it is (Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;)Lorg/apache/pekko/stream/scaladsl/Flow<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;Lorg/apache/pekko/NotUsed;>; rather than (Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;)Lorg/apache/pekko/stream/scaladsl/Flow<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;Ljava/lang/String;Lorg/apache/pekko/NotUsed;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer.flow")
[error]  * method flow(java.lang.String,org.apache.pekko.stream.connectors.ironmq.IronMqSettings)org.apache.pekko.stream.scaladsl.Flow in object org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer has a different generic signature in current version, where it is (Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;)Lorg/apache/pekko/stream/scaladsl/Flow<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;Lorg/apache/pekko/NotUsed;>; rather than (Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;)Lorg/apache/pekko/stream/scaladsl/Flow<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;Ljava/lang/String;Lorg/apache/pekko/NotUsed;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer.flow")
[error]  * method atLeastOnceFlow(java.lang.String,org.apache.pekko.stream.connectors.ironmq.IronMqSettings)org.apache.pekko.stream.scaladsl.Flow in object org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer has a different generic signature in current version, where it is (Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;)Lorg/apache/pekko/stream/scaladsl/Flow<Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;Lorg/apache/pekko/stream/connectors/ironmq/scaladsl/Committable;>;Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;Lorg/apache/pekko/NotUsed;>; rather than (Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;)Lorg/apache/pekko/stream/scaladsl/Flow<Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;Lorg/apache/pekko/stream/connectors/ironmq/scaladsl/Committable;>;Ljava/lang/String;Lorg/apache/pekko/NotUsed;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer.atLeastOnceFlow")
[error]  * method atLeastOnceFlow(java.lang.String,org.apache.pekko.stream.connectors.ironmq.IronMqSettings,org.apache.pekko.stream.scaladsl.Flow)org.apache.pekko.stream.scaladsl.Flow in object org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer has a different generic signature in current version, where it is <ToCommit:Ljava/lang/Object;CommitResult:Ljava/lang/Object;CommitMat:Ljava/lang/Object;>(Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;Lorg/apache/pekko/stream/scaladsl/Flow<TToCommit;TCommitResult;TCommitMat;>;)Lorg/apache/pekko/stream/scaladsl/Flow<Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;TToCommit;>;Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/Message$Id;TCommitResult;>;TCommitMat;>; rather than <ToCommit:Ljava/lang/Object;CommitResult:Ljava/lang/Object;CommitMat:Ljava/lang/Object;>(Ljava/lang/String;Lorg/apache/pekko/stream/connectors/ironmq/IronMqSettings;Lorg/apache/pekko/stream/scaladsl/Flow<TToCommit;TCommitResult;TCommitMat;>;)Lorg/apache/pekko/stream/scaladsl/Flow<Lscala/Tuple2<Lorg/apache/pekko/stream/connectors/ironmq/PushMessage;TToCommit;>;Lscala/Tuple2<Ljava/lang/String;TCommitResult;>;TCommitMat;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.ironmq.scaladsl.IronMqProducer.atLeastOnceFlow")
[error] pekko-connectors-kinesis: Failed binary compatibility check against org.apache.pekko:pekko-connectors-kinesis_3:1.0.2! Found 2 potential problems
[error]  * static method sharded(scala.Function1,org.apache.pekko.stream.connectors.kinesis.KinesisSchedulerSourceSettings)org.apache.pekko.stream.scaladsl.SubFlow in class org.apache.pekko.stream.connectors.kinesis.scaladsl.KinesisSchedulerSource has a different generic signature in current version, where it is (Lscala/Function1<Lsoftware/amazon/kinesis/processor/ShardRecordProcessorFactory;Lsoftware/amazon/kinesis/coordinator/Scheduler;>;Lorg/apache/pekko/stream/connectors/kinesis/KinesisSchedulerSourceSettings;)Lorg/apache/pekko/stream/scaladsl/SubFlow<Lorg/apache/pekko/stream/connectors/kinesis/CommittableRecord;Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;*Lorg/apache/pekko/stream/scaladsl/RunnableGraph<Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;>;>; rather than (Lscala/Function1<Lsoftware/amazon/kinesis/processor/ShardRecordProcessorFactory;Lsoftware/amazon/kinesis/coordinator/Scheduler;>;Lorg/apache/pekko/stream/connectors/kinesis/KinesisSchedulerSourceSettings;)Lorg/apache/pekko/stream/scaladsl/SubFlow<Lorg/apache/pekko/stream/connectors/kinesis/CommittableRecord;Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;Lorg/apache/pekko/stream/scaladsl/Source<Ljava/lang/Object;Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;>;Lorg/apache/pekko/stream/scaladsl/RunnableGraph<Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;>;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.kinesis.scaladsl.KinesisSchedulerSource.sharded")
[error]  * method sharded(scala.Function1,org.apache.pekko.stream.connectors.kinesis.KinesisSchedulerSourceSettings)org.apache.pekko.stream.scaladsl.SubFlow in object org.apache.pekko.stream.connectors.kinesis.scaladsl.KinesisSchedulerSource has a different generic signature in current version, where it is (Lscala/Function1<Lsoftware/amazon/kinesis/processor/ShardRecordProcessorFactory;Lsoftware/amazon/kinesis/coordinator/Scheduler;>;Lorg/apache/pekko/stream/connectors/kinesis/KinesisSchedulerSourceSettings;)Lorg/apache/pekko/stream/scaladsl/SubFlow<Lorg/apache/pekko/stream/connectors/kinesis/CommittableRecord;Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;*Lorg/apache/pekko/stream/scaladsl/RunnableGraph<Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;>;>; rather than (Lscala/Function1<Lsoftware/amazon/kinesis/processor/ShardRecordProcessorFactory;Lsoftware/amazon/kinesis/coordinator/Scheduler;>;Lorg/apache/pekko/stream/connectors/kinesis/KinesisSchedulerSourceSettings;)Lorg/apache/pekko/stream/scaladsl/SubFlow<Lorg/apache/pekko/stream/connectors/kinesis/CommittableRecord;Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;Lorg/apache/pekko/stream/scaladsl/Source<Ljava/lang/Object;Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;>;Lorg/apache/pekko/stream/scaladsl/RunnableGraph<Lscala/concurrent/Future<Lsoftware/amazon/kinesis/coordinator/Scheduler;>;>;>;. See https://github.com/lightbend/mima#incompatiblesignatureproblem
[error]    filter with: ProblemFilters.exclude[IncompatibleSignatureProblem]("org.apache.pekko.stream.connectors.kinesis.scaladsl.KinesisSchedulerSource.sharded")
```

**Comment by WojciechMazur** [comment]
I believe the issues are related to the https://github.com/scala/scala3/pull/20463. We're aware that this change can lead to mima issues, but during the Compiler Core meeting we've decided to include it in the LTS backports. This change is assumed to be a bugfix which allows the align of the behaviour with Scala 2 (it was fixed in 2.12.9, almost 5 years ago, it's a shame it was not forward-ported to Scala 3 before)

**Comment by pjfanning** [comment]
see #842

**Pull request closed without merging**
