### PR TITLE
link validator CI failing

### PR DESCRIPTION
**Pull request by pjfanning**
* https://github.com/apache/pekko-connectors/actions/workflows/link-validator.yml
* for this repo, link validation CI is only done once a week on a schedule - not for every PR
* the job has been failing for a while but #899 made it worse
* raised #920 and #921 to follow up on remaining issues

### CODE REVIEW

**Comment by raboof** [comment]
(in pekko-grpc I had to remove the `./` from `root-dir`: https://github.com/apache/pekko-grpc/pull/400/files#diff-2a4ceebcb5b6c8bab1e5727bc9d87843f8f5c73f41c024b37acea23edb532ce7R4)

**Comment by pjfanning** [comment]
thanks @raboof - that helps progress.

There are some issues not associated with license report and I'll look at those now.

```
## Non-https pages
http://reactivemongo.org/
 - docs/pekko-connectors/snapshot/mongodb.html

http://www.scala-lang.org/api/2.13.15/scala/concurrent/Future.html
 - docs/pekko-connectors/snapshot/ftp.html
 - docs/pekko-connectors/snapshot/mqtt.html

http://www.scala-lang.org/api/2.13.15/scala/util/Try.html
 - docs/pekko-connectors/snapshot/dynamodb.html
```

**Comment by pjfanning** [comment]
Still hitting issues with scaladoc links.

```
https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/GrpcChannel.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/PublisherClient$.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/SubscriberClient$.html
 - ... 7 more

https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/GrpcClientSettings.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/PublisherClient$.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/SubscriberClient$.html
 - ... 7 more

https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/ServiceDescription.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/Publisher$$MethodDescriptors$.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/Publisher$$Serializers$.html
 - ... 33 more

https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/javadsl/PekkoGrpcClient.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/PublisherClient.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/SchemaServiceClient.html
 - ... 14 more

https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/javadsl/SingleResponseRequestBuilder.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/PublisherClient.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/PublisherClientPowerApi.html
 - ... 8 more

https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/javadsl/StreamResponseRequestBuilder.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/SubscriberClient.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/SubscriberClientPowerApi.html
 - ... 10 more

https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/scaladsl/PekkoGrpcClient.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/PublisherClient.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/SubscriberClient.html
 - ... 15 more

https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/scaladsl/ScalapbProtobufSerializer.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/Publisher$$Serializers$.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/Subscriber$$Serializers$.html
 - ... 7 more

https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/scaladsl/SingleResponseRequestBuilder.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/PublisherClient.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/PublisherClientPowerApi.html
 - ... 8 more

https://pekko.apache.org/api/pekko-grpc/1.1.1/org/apache/pekko/grpc/org/apache/pekko/grpc/scaladsl/StreamResponseRequestBuilder.html status 404 Not Found
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/SubscriberClient.html
 - api/pekko-connectors/snapshot/com/google/pubsub/v1/pubsub/SubscriberClientPowerApi.html
 - ... 10 more

https://pekko.apache.org/api/pekko-http/1.1.0/org/apache/pekko/http/impl/util/Renderable.html status 404 Not Found
 - api/pekko-connectors/snapshot/org/apache/pekko/stream/connectors/google/scaladsl/X$minusUpload$minusContent$minusType.html

https://pekko.apache.org/api/pekko-http/1.1.0/org/apache/pekko/http/impl/util/Rendering.html status 404 Not Found
 - api/pekko-connectors/snapshot/org/apache/pekko/stream/connectors/google/scaladsl/X$minusUpload$minusContent$minusType.html

https://pekko.apache.org/api/pekko-http/1.1.0/org/apache/pekko/http/impl/util/ToStringRenderable.html status 404 Not Found
 - api/pekko-connectors/snapshot/org/apache/pekko/stream/connectors/google/scaladsl/X$minusUpload$minusContent$minusType.html

```

**Comment by raboof** [comment]
> Still hitting issues with scaladoc links.

I suppose we can add them to `ignore-prefixes` and create an issue for the problem?

**Review by raboof — APPROVED** [review]
Great!

**Pull request merged**
